#! /bin/sh

export DESKTOP_SESSION=bspwm

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI
bspc monitor -d '' '' '' '' '' ''

bspc config border_width        10
bspc config window_gap          9

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focused_border_color \#404B66
bspc config normal_border_color \#0b151d

bspc rule -a '*' desktop='^5' state=floating

bspc rule -a Alacritty desktop='^1' state=tiled follow=on focus=on

bspc rule -a Ungoogled-chromium desktop='^2' state=tiled follow=on focus=on
bspc rule -a Firefox desktop='^2' state=tiled follow=on focus=on

bspc rule -a Soffice desktop='^3' state=tiled follow=on focus=on
bspc rule -a Apostrophe desktop='^3' state=tiled follow=on focus=on

bspc rule -a Steam desktop='^4' follow=on focus=on

bspc config external_rules_command $HOME/.config/bspwm/external_rules.zsh

xsetroot -cursor_name left_ptr

feh --bg-scale $HOME/Downloads/aisberg-voda-art-ostrov-led-arktika-krasota.jpg
pgrep -x picom > /dev/null || picom --experimental-backends &
pgrep -x dunst > /dev/null || dunst &
$HOME/.config/polybar/launch.sh
